// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.Automations.Infrastructure;

#nullable disable

namespace Senswave.Automations.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationsContext))]
    [Migration("20240914150433_Annotations")]
    partial class Annotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Automations")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionsConnector")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HomesReferenceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Automations", "Automations");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.OwnsMany("Senswave.Automations.Domain.ValueObjects.AutomationCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AutomationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<JsonDocument>("ConditionConfiguration")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ConditionType")
                                .HasColumnType("integer");

                            b1.HasKey("AutomationId", "Id");

                            b1.ToTable("AutomationCondition", "Automations");

                            b1.WithOwner()
                                .HasForeignKey("AutomationId");
                        });

                    b.OwnsMany("Senswave.Automations.Domain.ValueObjects.AutomationResult", "Results", b1 =>
                        {
                            b1.Property<Guid>("AutomationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<JsonDocument>("ResultConfiguration")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ResultType")
                                .HasColumnType("integer");

                            b1.HasKey("AutomationId", "Id");

                            b1.ToTable("AutomationResult", "Automations");

                            b1.WithOwner()
                                .HasForeignKey("AutomationId");
                        });

                    b.OwnsOne("Senswave.Automations.Domain.ValueObjects.AutomationView", "View", b1 =>
                        {
                            b1.Property<Guid>("AutomationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("Icon")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("AutomationId");

                            b1.ToTable("Automations", "Automations");

                            b1.WithOwner("Automation")
                                .HasForeignKey("AutomationId");

                            b1.Navigation("Automation");
                        });

                    b.Navigation("Conditions");

                    b.Navigation("Results");

                    b.Navigation("View")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
