// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.Automations.Infrastructure;

#nullable disable

namespace Senswave.Automations.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationsContext))]
    [Migration("20240521173726_AutomationInitialization")]
    partial class AutomationInitialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionsConnector")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HomeReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Automations");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.OwnsMany("Senswave.Automations.Domain.ValueObjects.AutomationCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AutomationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<JsonDocument>("ConditionConfiguration")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ConditionType")
                                .HasColumnType("integer");

                            b1.HasKey("AutomationId", "Id");

                            b1.ToTable("AutomationCondition");

                            b1.WithOwner()
                                .HasForeignKey("AutomationId");
                        });

                    b.OwnsMany("Senswave.Automations.Domain.ValueObjects.AutomationResult", "Results", b1 =>
                        {
                            b1.Property<Guid>("AutomationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<JsonDocument>("ResultConfiguration")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ResultType")
                                .HasColumnType("integer");

                            b1.HasKey("AutomationId", "Id");

                            b1.ToTable("AutomationResult");

                            b1.WithOwner()
                                .HasForeignKey("AutomationId");
                        });

                    b.Navigation("Conditions");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
