// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.Automations.Infrastructure;

#nullable disable

namespace Senswave.Automations.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationsContext))]
    [Migration("20250712093251_SplitAutomationsToThree")]
    partial class SplitAutomationsToThree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Automations")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionsConnector")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HomesReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name", "HomesReferenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Home_AutomationName");

                    b.ToTable("Automations", "Automations");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.AutomationCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionConfiguration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConditionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId");

                    b.ToTable("AutomationConditions", "Automations");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.AutomationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueToSend")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId");

                    b.ToTable("AutomationResults", "Automations");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.AutomationCondition", b =>
                {
                    b.HasOne("Senswave.Automations.Domain.Entities.Automation", "Automation")
                        .WithMany("Conditions")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automation");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.AutomationResult", b =>
                {
                    b.HasOne("Senswave.Automations.Domain.Entities.Automation", "Automation")
                        .WithMany("Results")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automation");
                });

            modelBuilder.Entity("Senswave.Automations.Domain.Entities.Automation", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
