// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.Devices.Infrastructure;

#nullable disable

namespace Senswave.Devices.Infrastructure.Migrations
{
    [DbContext(typeof(DevicesContext))]
    [Migration("20260408070051_DevicePresence")]
    partial class DevicePresence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Devices")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.Devices.Domain.Dashboards.Entities.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Name")
                        .IsUnique();

                    b.ToTable("Dashboards", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HomeReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PresenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomReferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HomeReferenceId");

                    b.ToTable("Devices", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.DevicePresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("OperationId");

                    b.ToTable("DevicePresence", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.DeviceTile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("OperationId");

                    b.ToTable("DeviceTiles", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.HomeReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HomeId", "OwnerId")
                        .IsUnique();

                    b.ToTable("HomeReferences", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.DataSourceDataReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceDataReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceDataReferenceId")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.ToTable("DataReferences", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DataReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataReferenceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Operations", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.ShareDevices.Entites.DeviceSharing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SharingType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceSharing", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Widgets.Entities.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Name")
                        .IsUnique();

                    b.ToTable("Widgets", "Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Dashboards.Entities.Dashboard", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithMany("Dashboards")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.Device", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.HomeReference", "HomeReference")
                        .WithMany("Devices")
                        .HasForeignKey("HomeReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeReference");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.DevicePresence", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithOne("Presence")
                        .HasForeignKey("Senswave.Devices.Domain.Devices.Entities.DevicePresence", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senswave.Devices.Domain.Operations.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.DeviceTile", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithOne("Tile")
                        .HasForeignKey("Senswave.Devices.Domain.Devices.Entities.DeviceTile", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Senswave.Devices.Domain.Operations.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.DataSourceDataReference", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithMany("DataReferences")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.Operation", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Operations.Entities.DataSourceDataReference", "DataReference")
                        .WithMany("Operations")
                        .HasForeignKey("DataReferenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithMany("Operations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Senswave.Devices.Domain.Operations.ValueObjects.OperationValue", "Values", b1 =>
                        {
                            b1.Property<Guid>("OperationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("InternalValue")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<DateTime>("ProcessedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("OperationId", "Id");

                            b1.ToTable("OperationValues", "Devices");

                            b1.WithOwner("Operation")
                                .HasForeignKey("OperationId");

                            b1.Navigation("Operation");
                        });

                    b.Navigation("DataReference");

                    b.Navigation("Device");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.ShareDevices.Entites.DeviceSharing", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Devices.Entities.Device", "Device")
                        .WithMany("DeviceSharings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Widgets.Entities.Widget", b =>
                {
                    b.HasOne("Senswave.Devices.Domain.Operations.Entities.Operation", "Operation")
                        .WithMany("Widgets")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.Device", b =>
                {
                    b.Navigation("Dashboards");

                    b.Navigation("DataReferences");

                    b.Navigation("DeviceSharings");

                    b.Navigation("Operations");

                    b.Navigation("Presence");

                    b.Navigation("Tile")
                        .IsRequired();
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Devices.Entities.HomeReference", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.DataSourceDataReference", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Senswave.Devices.Domain.Operations.Entities.Operation", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
