// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.DataSources.Infrastructure;

#nullable disable

namespace Senswave.DataSources.Infrastructure.Migrations
{
    [DbContext(typeof(DataSourcesContext))]
    [Migration("20240714135141_BrokerConnection")]
    partial class BrokerConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DataSources")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Brokers", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId")
                        .IsUnique();

                    b.ToTable("Connections", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Logs", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("Sessions", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Subscribtion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Subscribtions", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.OwnsOne("Senswave.DataSources.Domain.Brokers.ValueObjects.BrokerInfo", "BrokerInfo", b1 =>
                        {
                            b1.Property<Guid>("BrokerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ClientName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Port")
                                .HasColumnType("integer");

                            b1.Property<int>("ProtocolVersion")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BrokerId");

                            b1.ToTable("BrokerInfo", "DataSources");

                            b1.WithOwner()
                                .HasForeignKey("BrokerId");
                        });

                    b.Navigation("BrokerInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Connection", b =>
                {
                    b.HasOne("Senswave.DataSources.Domain.Brokers.Entities.Broker", "Broker")
                        .WithOne("Connection")
                        .HasForeignKey("Senswave.DataSources.Domain.Brokers.Entities.Connection", "BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Log", b =>
                {
                    b.HasOne("Senswave.DataSources.Domain.Brokers.Entities.Session", "Session")
                        .WithMany("Logs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Session", b =>
                {
                    b.HasOne("Senswave.DataSources.Domain.Brokers.Entities.Connection", "Connection")
                        .WithMany("Sessions")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Subscribtion", b =>
                {
                    b.HasOne("Senswave.DataSources.Domain.Brokers.Entities.Broker", "Broker")
                        .WithMany("Subscribtions")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.Navigation("Connection")
                        .IsRequired();

                    b.Navigation("Subscribtions");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Connection", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Session", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
