// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.DataSources.Infrastructure;

#nullable disable

namespace Senswave.DataSources.Infrastructure.Migrations
{
    [DbContext(typeof(DataSourcesContext))]
    [Migration("20240521083441_ImprovedDataSource")]
    partial class ImprovedDataSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DataSources")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Brokers", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Subscribtion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Subscribtions", "DataSources");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.OwnsOne("Senswave.DataSources.Domain.Brokers.ValueObjects.BrokerCredentials", "BrokerCredentials", b1 =>
                        {
                            b1.Property<Guid>("BrokerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BrokerId");

                            b1.ToTable("BrokerCredentials", "DataSources");

                            b1.WithOwner()
                                .HasForeignKey("BrokerId");
                        });

                    b.OwnsOne("Senswave.DataSources.Domain.Brokers.ValueObjects.BrokerInfo", "BrokerInfo", b1 =>
                        {
                            b1.Property<Guid>("BrokerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ClientName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Port")
                                .HasColumnType("integer");

                            b1.Property<int>("ProtocolVersion")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BrokerId");

                            b1.ToTable("BrokerInfo", "DataSources");

                            b1.WithOwner()
                                .HasForeignKey("BrokerId");
                        });

                    b.Navigation("BrokerCredentials")
                        .IsRequired();

                    b.Navigation("BrokerInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Subscribtion", b =>
                {
                    b.HasOne("Senswave.DataSources.Domain.Brokers.Entities.Broker", "Broker")
                        .WithMany("Subscribtions")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Senswave.DataSources.Domain.Brokers.ValueObjects.SubscribtionEvent", "Events", b1 =>
                        {
                            b1.Property<Guid>("SubscribtionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Payload")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ReceivedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SubscribtionId", "Id");

                            b1.ToTable("SubscribtionEvents", "DataSources");

                            b1.WithOwner("Subscribtion")
                                .HasForeignKey("SubscribtionId");

                            b1.Navigation("Subscribtion");
                        });

                    b.Navigation("Broker");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Senswave.DataSources.Domain.Brokers.Entities.Broker", b =>
                {
                    b.Navigation("Subscribtions");
                });
#pragma warning restore 612, 618
        }
    }
}
