// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Senswave.Homes.Infrastructure;

#nullable disable

namespace Senswave.Homes.Infrastructure.Migrations
{
    [DbContext(typeof(HomesContext))]
    [Migration("20250626161501_SharingExpiration")]
    partial class SharingExpiration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Homes")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Senswave.Homes.Domain.Homes.Entities.DataSourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId")
                        .IsUnique();

                    b.HasIndex("HomeId")
                        .IsUnique();

                    b.ToTable("DataSourceReference", "Homes");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Homes.Entities.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("Home_OwnerId_Name");

                    b.ToTable("Homes", "Homes");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Rooms.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("Room_HomeId_Name");

                    b.ToTable("Rooms", "Homes");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Sharings.Entities.HomeSharing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SharingType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId", "HomeId")
                        .IsUnique()
                        .HasDatabaseName("HomeSharing_UserId_HomeId");

                    b.ToTable("HomeSharing", "Homes");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Sharings.Entities.HomeSharingInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HomeId", "FriendId")
                        .IsUnique()
                        .HasDatabaseName("HomeSharingInvitation_HomeId_FriendId");

                    b.ToTable("HomeSharingInvitation", "Homes");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Homes.Entities.DataSourceReference", b =>
                {
                    b.HasOne("Senswave.Homes.Domain.Homes.Entities.Home", "Home")
                        .WithOne("DataSourceReference")
                        .HasForeignKey("Senswave.Homes.Domain.Homes.Entities.DataSourceReference", "HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Homes.Entities.Home", b =>
                {
                    b.OwnsOne("Senswave.Homes.Domain.Homes.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("HomeId");

                            b1.ToTable("Location", "Homes");

                            b1.WithOwner("Home")
                                .HasForeignKey("HomeId");

                            b1.Navigation("Home");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Rooms.Entities.Room", b =>
                {
                    b.HasOne("Senswave.Homes.Domain.Homes.Entities.Home", "Home")
                        .WithMany("Rooms")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Sharings.Entities.HomeSharing", b =>
                {
                    b.HasOne("Senswave.Homes.Domain.Homes.Entities.Home", "Home")
                        .WithMany("HomeSharing")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Senswave.Homes.Domain.Homes.Entities.Home", b =>
                {
                    b.Navigation("DataSourceReference");

                    b.Navigation("HomeSharing");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
