global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
global using Senswave.Abstractions.Contexts;
global using Senswave.Infrastructure.Web.Endpoints;
global using Senswave.Infrastructure.Web.Extensions;